import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "bun:test";

import { defineStudioGeneratedTarget, studioCodegenTargets } from "@flexweave/studio/codegen";
import { defineStudioConfig, validateStudioConfig } from "@flexweave/studio/config";
import { loadStudioConfig } from "@flexweave/studio/config/load";
import { defineStudioExtension } from "@flexweave/studio/extensions";
import { codegenStudioProject } from "@flexweave/studio/workflows";

import {
  copyMinimalFixture,
  extensionFixtureRoot,
  fixtureRoot,
  generatedTargetFixtureConfigPath,
  pathContains,
} from "./support/studio-fixtures";

test("codegen check detects stale, missing, and unexpected managed files without writing", async () => {
  const root = copyMinimalFixture();
  const configPath = join(root, "studio.config.ts");
  const stalePath = join(root, "generated/abilities/generated.rs");
  const missingPath = join(root, "generated/tags/generated.rs");
  const unexpectedPath = join(root, "generated/effects/unused.rs");
  const originalStale = readFileSync(stalePath, "utf-8");

  writeFileSync(stalePath, `${originalStale}// stale\n`);
  rmSync(missingPath);
  writeFileSync(
    unexpectedPath,
    '//! Generated by Flexweave Studio for effects.\n\npub const OLD: &str = "old";\n',
  );

  const result = await codegenStudioProject({ check: true, configPath });

  expect(result.ok).toBe(false);
  expect(result.diagnostics.map((diagnostic) => diagnostic.code).toSorted()).toEqual([
    "generated-missing",
    "generated-stale",
    "generated-unexpected",
  ]);
  expect(readFileSync(stalePath, "utf-8")).toBe(`${originalStale}// stale\n`);
  expect(existsSync(missingPath)).toBe(false);
  expect(existsSync(unexpectedPath)).toBe(true);
});

test("extension generated targets run through the target registry", async () => {
  const checked = await codegenStudioProject({
    check: true,
    configPath: generatedTargetFixtureConfigPath,
    targets: ["synthetic-summary"],
  });
  expect(checked.ok).toBe(true);
  expect(checked.targets.map((target) => target.target)).toEqual(["tags", "synthetic-summary"]);
  expect(checked.targets.find((target) => target.target === "synthetic-summary")?.files).toEqual([
    {
      path: join(fixtureRoot, "generated/synthetic/summary.txt"),
      status: "fresh",
      target: "synthetic-summary",
    },
  ]);

  const unknown = await codegenStudioProject({
    check: true,
    configPath: generatedTargetFixtureConfigPath,
    targets: ["unknown"],
  });
  expect(unknown.ok).toBe(false);
  expect(unknown.diagnostics[0]).toMatchObject({
    code: "unknown-codegen-target",
  });
  expect(unknown.diagnostics[0]?.hint).toContain("synthetic-summary");
});

test("extension targets can replace disabled built-in target ids", async () => {
  const root = copyMinimalFixture();
  const shadowOutputDir = join(root, "generated/shadow-tags");
  mkdirSync(shadowOutputDir, { recursive: true });
  writeFileSync(join(shadowOutputDir, "shadow.txt"), "consumer tags\n");

  const generatedTarget = defineStudioGeneratedTarget({
    id: "tags",
    label: "Consumer tags",
    plan: ({ outputDir }) => ({
      files: [
        {
          path: join(outputDir, "shadow.txt"),
          value: "consumer tags\n",
        },
      ],
    }),
  });
  const validated = validateStudioConfig(
    defineStudioConfig({
      catalogRoot: "catalog",
      codegen: {
        builtInTargets: [],
        outputDirs: {
          tags: "generated/shadow-tags",
        },
      },
      extensions: [
        defineStudioExtension({
          generatedTargets: [generatedTarget],
          id: "consumer-generated-targets",
        }),
      ],
      hooks: {
        dir: "runtime-hooks",
      },
      rust: {
        flexweaveModule: "flexweave",
      },
    }),
    {
      configDir: root,
      configPath: join(root, "studio.config.ts"),
    },
  );

  expect(validated.ok).toBe(true);
  expect(validated.config?.codegen.builtInTargets).toEqual([]);

  const checked = await codegenStudioProject({
    check: true,
    config: validated.config,
  });
  expect(checked.ok).toBe(true);
  expect(checked.targets).toEqual([
    {
      files: [
        {
          path: join(shadowOutputDir, "shadow.txt"),
          status: "fresh",
          target: "tags",
        },
      ],
      label: "Consumer tags",
      target: "tags",
    },
  ]);
});

test("extension Rust binding config feeds extension generated targets", async () => {
  const checked = await codegenStudioProject({
    check: true,
    configPath: generatedTargetFixtureConfigPath,
    targets: ["synthetic-rust"],
  });
  expect(checked.ok).toBe(true);
  expect(checked.targets).toEqual([
    {
      files: [
        {
          path: join(fixtureRoot, "generated/synthetic-rust/synthetic.rs"),
          status: "fresh",
          target: "synthetic-rust",
        },
      ],
      label: "Synthetic Rust binding",
      target: "synthetic-rust",
    },
  ]);

  const invalid = await loadStudioConfig({
    configPath: join(fixtureRoot, "invalid-rust-binding.config.ts"),
  });
  expect(invalid.ok).toBe(false);
  expect(invalid.diagnostics).toContainEqual(
    expect.objectContaining({
      code: "invalid-synthetic-rust-binding",
      field: "rust.bindings.synthetic.module",
    }),
  );
});

test("generated target registry blocks out-of-bounds target plans", async () => {
  const result = await codegenStudioProject({
    check: true,
    configPath: join(extensionFixtureRoot, "out-of-bounds-target.config.ts"),
    targets: ["out-of-bounds"],
  });

  expect(result.ok).toBe(false);
  expect(result.diagnostics).toContainEqual(
    expect.objectContaining({
      code: "generated-output-out-of-bounds",
    }),
  );
  expect(existsSync(join(extensionFixtureRoot, "generated/outside.txt"))).toBe(false);
});

test("codegen writes only configured outputs, preserves hooks, and reports orphan hooks", async () => {
  const root = copyMinimalFixture();
  const configPath = join(root, "studio.config.ts");
  const hookPath = join(root, "runtime-hooks/minimal_execution.rs");
  const hookValue = "//! consumer-owned hook\n\npub fn minimal_execution() {}\n";
  const libPath = join(root, "runtime-hooks/lib.rs");
  const modPath = join(root, "runtime-hooks/mod.rs");
  const orphanPath = join(root, "runtime-hooks/orphan.rs");

  rmSync(join(root, "generated/abilities/generated.rs"));
  writeFileSync(hookPath, hookValue);
  writeFileSync(libPath, "//! hook module index\n");
  writeFileSync(modPath, "//! hook module index\n");
  writeFileSync(orphanPath, "//! orphan runtime hook\n");

  const result = await codegenStudioProject({ configPath });
  const loaded = await loadStudioConfig({ configPath });
  expect(loaded.ok).toBe(true);
  const outputDirs = Object.values(loaded.config?.paths.codegen.outputDirs ?? {});
  const hookDirs = [loaded.config?.paths.hooks.dir, loaded.config?.paths.hooks.testStubsDir].filter(
    (path): path is string => typeof path === "string",
  );

  expect(result.ok).toBe(true);
  expect(existsSync(join(root, "generated/abilities/generated.rs"))).toBe(true);
  expect(readFileSync(hookPath, "utf-8")).toBe(hookValue);
  expect(
    result.diagnostics.filter((diagnostic) => diagnostic.code === "orphan-runtime-hook"),
  ).toEqual([
    expect.objectContaining({
      path: "runtime-hooks/orphan.rs",
    }),
  ]);
  expect(existsSync(orphanPath)).toBe(true);
  for (const target of studioCodegenTargets) {
    expect(
      result.targets
        .find((summary) => summary.target === target)
        ?.files.every((file) => outputDirs.some((outputDir) => pathContains(outputDir, file.path))),
    ).toBe(true);
  }
  expect(
    result.hooks.every((hook) => hookDirs.some((hookDir) => pathContains(hookDir, hook.path))),
  ).toBe(true);
});

test("codegen rolls back generated files and runtime hook stubs when hook writes fail", async () => {
  const root = copyMinimalFixture();
  const configPath = join(root, "studio.config.ts");
  const generatedPath = join(root, "generated/executions/generated.rs");
  const originalGenerated = readFileSync(generatedPath, "utf-8");
  const hookPath = join(root, "runtime-hooks/rollback_runtime_hook.rs");
  const testStubsRoot = join(root, "generated-hook-tests");
  const testHookPath = join(testStubsRoot, "rollback_runtime_hook.rs");

  writeFileSync(
    join(root, "catalog/executions/rollback_execution.json"),
    `${JSON.stringify({
      hook: "rollback_runtime_hook",
      id: "rollback_execution",
      kind: "execution",
      label: "Rollback execution",
    })}\n`,
  );
  rmSync(testStubsRoot, { force: true, recursive: true });
  writeFileSync(testStubsRoot, "not a directory\n");

  const result = await codegenStudioProject({ configPath, targets: ["executions"] });

  expect(result.ok).toBe(false);
  expect(result.diagnostics).toContainEqual(
    expect.objectContaining({ code: "codegen-write-failed" }),
  );
  expect(readFileSync(generatedPath, "utf-8")).toBe(originalGenerated);
  expect(existsSync(hookPath)).toBe(false);
  expect(existsSync(testHookPath)).toBe(false);
  expect(readFileSync(testStubsRoot, "utf-8")).toBe("not a directory\n");
});
