import { join } from "node:path";

import { defineStudioGeneratedTarget } from "@flexweave/studio/codegen";
import { defineStudioConfig } from "@flexweave/studio/config";
import { defineStudioExtension } from "@flexweave/studio/extensions";

const outOfBoundsTarget = defineStudioGeneratedTarget({
  id: "out-of-bounds",
  label: "Out of bounds target",
  plan: ({ outputDir }) => ({
    files: [
      {
        path: join(outputDir, "../outside.txt"),
        value: "Generated by Flexweave Studio outside the configured root.\n",
      },
    ],
  }),
});

const outOfBoundsExtension = defineStudioExtension({
  generatedTargets: [outOfBoundsTarget],
  id: "out-of-bounds-extension",
});

export default defineStudioConfig({
  catalogRoot: "catalog",
  codegen: {
    outputDirs: {
      abilities: "generated/abilities",
      effects: "generated/effects",
      executions: "generated/executions",
      modifiers: "generated/modifiers",
      "out-of-bounds": "generated/out-of-bounds",
      reference: "generated/reference",
      tags: "generated/tags",
    },
  },
  extensions: [outOfBoundsExtension],
  hooks: {
    dir: "runtime-hooks",
  },
  rust: {
    flexweaveModule: "flexweave",
  },
});
