import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { defineStudioGeneratedTarget } from "@flexweave/studio/codegen";
import {
  defineStudioContentMapper,
  defineStudioDataAdapter,
  defineStudioExtension,
  defineStudioExtensionMigration,
  defineStudioHostAppContribution,
  studioSourceLocationLabel,
} from "@flexweave/studio/extensions";
import type { StudioDiagnostic, StudioSourceRecord } from "@flexweave/studio/extensions";

const optionString = (
  options: Record<string, unknown> | undefined,
  key: string,
): string | undefined => {
  const value = options?.[key];
  return typeof value === "string" && value.length > 0 ? value : undefined;
};

const isObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const sourceRecordDiagnostic = (record: StudioSourceRecord): StudioDiagnostic => ({
  code: "synthetic-source-invalid",
  message: `Synthetic source record ${record.id} is invalid.`,
  path: studioSourceLocationLabel(record.location),
  severity: "error",
  source: record.location,
});

export const syntheticFileAdapter = defineStudioDataAdapter({
  capabilities: ["read"],
  id: "synthetic-file",
  label: "Synthetic file adapter",
  load: ({ config, source }) => {
    const path = optionString(source.options, "path");
    if (!path) {
      throw new Error("Expected source option path.");
    }

    const value = JSON.parse(readFileSync(join(config.configDir, path), "utf-8"));
    if (!isObject(value) || typeof value.id !== "string") {
      throw new Error("Expected file-backed source record with an id.");
    }

    return {
      records: [
        {
          id: value.id,
          kind: "synthetic.file",
          location: {
            jsonPointer: "/",
            path,
          },
          value,
        },
      ],
    };
  },
});

export const syntheticTableAdapter = defineStudioDataAdapter({
  capabilities: ["read", "schema", "write"],
  id: "synthetic-table",
  label: "Synthetic table adapter",
  load: ({ source }) => {
    const rows = Array.isArray(source.options?.rows) ? source.options.rows : [];

    return {
      records: rows.map((row, index) => {
        if (!isObject(row) || typeof row.id !== "string") {
          throw new Error(`Expected table row ${index + 2} to contain an id.`);
        }

        return {
          id: row.id,
          kind: "synthetic.table",
          location: {
            column: 1,
            field: "id",
            row: index + 2,
            sheet: "synthetic-table",
          },
          value: row,
        };
      }),
    };
  },
  write: ({ records }) => ({ records }),
});

export const syntheticTableContentMapper = defineStudioContentMapper({
  id: "synthetic-table-content-mapper",
  label: "Synthetic table content mapper",
  map: ({ snapshots }) => ({
    records: snapshots.flatMap((snapshot) =>
      snapshot.records
        .filter(
          (record) =>
            record.kind === "synthetic.table" &&
            isObject(record.value) &&
            record.value.contentKind === "tag",
        )
        .map((record) => {
          const value = isObject(record.value) ? record.value : {};
          return {
            expectedKind: "tags",
            location: record.location,
            path: studioSourceLocationLabel(record.location),
            sourceRecord: record,
            value: {
              id: String(value.id),
              kind: "tag",
              label: String(value.label),
            },
          };
        }),
    ),
  }),
});

export const syntheticSummaryTarget = defineStudioGeneratedTarget({
  cleanup: "managed-files",
  dependencies: ["tags"],
  id: "synthetic-summary",
  label: "Synthetic generated summary",
  plan: ({ content, outputDir }) => {
    const recordCount = Array.isArray((content as { records?: unknown[] }).records)
      ? (content as { records: unknown[] }).records.length
      : 0;

    return {
      files: [
        {
          path: join(outputDir, "summary.txt"),
          value: [
            "Generated by Flexweave Studio synthetic target.",
            `Records: ${recordCount}`,
            "",
          ].join("\n"),
        },
      ],
    };
  },
});

export const syntheticRustTarget = defineStudioGeneratedTarget({
  cleanup: "managed-files",
  id: "synthetic-rust",
  label: "Synthetic Rust binding",
  plan: ({ config, outputDir }) => {
    const { rust } = config as {
      rust?: {
        bindings?: Record<string, unknown>;
        preludeImports?: string[];
      };
    };
    const binding = rust?.bindings?.synthetic;
    const module =
      typeof binding === "object" &&
      binding !== null &&
      !Array.isArray(binding) &&
      typeof (binding as { module?: unknown }).module === "string"
        ? (binding as { module: string }).module
        : "synthetic_runtime";

    return {
      files: [
        {
          path: join(outputDir, "synthetic.rs"),
          value: [
            "//! Generated by Flexweave Studio synthetic Rust target.",
            "//! Do not edit manually.",
            "",
            ...(rust?.preludeImports ?? []).map((item) => `use ${item};`),
            `pub const SYNTHETIC_MODULE: &str = "${module}";`,
            "",
          ].join("\n"),
        },
      ],
    };
  },
});

export const syntheticRustBindingConfig = {
  namespace: "synthetic",
  validate: ({ value }: { value: unknown }) => {
    if (
      typeof value === "object" &&
      value !== null &&
      !Array.isArray(value) &&
      typeof (value as { module?: unknown }).module === "string" &&
      (value as { module: string }).module.length > 0
    ) {
      return [];
    }

    return [
      {
        code: "invalid-synthetic-rust-binding",
        field: "rust.bindings.synthetic.module",
        message: "Synthetic Rust binding config must declare a non-empty module string.",
        severity: "error" as const,
      },
    ];
  },
};

export const syntheticHostAppContribution = defineStudioHostAppContribution({
  authoring: {
    areas: [
      {
        description: "Synthetic source records loaded through extension data adapters.",
        editorId: "synthetic-source-records",
        id: "synthetic-sources",
        label: "Synthetic sources",
      },
    ],
    editors: [
      {
        areaId: "synthetic-sources",
        commandName: "list",
        description: "Review normalized content mapped from synthetic source data.",
        id: "synthetic-source-records",
        label: "Synthetic source records",
        recordKind: "tags",
      },
    ],
  },
  codegenTargets: [
    {
      description: "Extension-owned generated summary output.",
      label: "Synthetic summary",
      outputLabel: "summary",
      target: "synthetic-summary",
    },
  ],
  diagnosticsPanels: [
    {
      commandName: "validate",
      description: "Diagnostics reported by synthetic source adapters and mappers.",
      id: "synthetic-source-diagnostics",
      label: "Synthetic source diagnostics",
    },
  ],
  generatedOutputPanels: [
    {
      description: "Generated files produced by the synthetic extension target.",
      id: "synthetic-summary-output",
      label: "Synthetic summary output",
      target: "synthetic-summary",
    },
  ],
  id: "synthetic-host-app",
  label: "Synthetic host app contribution",
  navigation: [
    {
      id: "synthetic",
      label: "Synthetic",
      links: [
        {
          href: "/sources/synthetic-table-source",
          id: "synthetic-table-source",
          label: "Table source",
        },
        {
          href: "/diagnostics/synthetic-source-diagnostics",
          id: "synthetic-source-diagnostics",
          label: "Source diagnostics",
        },
      ],
    },
  ],
  sourceViews: [
    {
      adapterId: "synthetic-table",
      description: "Rows loaded from the synthetic table adapter.",
      id: "synthetic-table-source",
      label: "Synthetic table source",
      sourceId: "table-backed",
    },
  ],
  workflowActions: [
    {
      commandName: "validate",
      id: "validate-synthetic-sources",
      label: "Validate synthetic sources",
      variant: "secondary",
    },
  ],
});

export const syntheticSchemaMigration = defineStudioExtensionMigration({
  fromVersion: 0,
  id: "synthetic-source-schema",
  label: "Synthetic source schema",
  migrate: ({ config }) => {
    const path = join(config.configDir, "sources/migration-state.json");
    const value = JSON.parse(readFileSync(path, "utf-8")) as { version?: unknown };
    const currentVersion = typeof value.version === "number" ? value.version : 0;

    if (currentVersion === 1) {
      return {
        skipped: ["Synthetic source schema is current."],
      };
    }

    if (currentVersion !== 0) {
      const message = `Unsupported synthetic source schema version ${currentVersion}; expected 0 or 1.`;
      return {
        diagnostics: [
          {
            code: "unsupported-extension-migration",
            message,
            path,
            severity: "error" as const,
          },
        ],
        manualFollowUps: [message],
      };
    }

    writeFileSync(path, `${JSON.stringify({ ...value, version: 1 }, null, 2)}\n`);
    return {
      applied: ["synthetic-source-extension: synthetic-source-schema 0 -> 1"],
      changedFiles: [path],
    };
  },
  toVersion: 1,
});

export const syntheticSourceExtension = defineStudioExtension({
  appContributions: [syntheticHostAppContribution],
  contentMappers: [syntheticTableContentMapper],
  dataAdapters: [syntheticFileAdapter, syntheticTableAdapter],
  generatedTargets: [syntheticSummaryTarget, syntheticRustTarget],
  id: "synthetic-source-extension",
  label: "Synthetic source extension",
  migrations: [syntheticSchemaMigration],
  rustBindingConfigs: [syntheticRustBindingConfig],
  validateSources: ({ snapshots }) =>
    snapshots
      .flatMap((snapshot) => snapshot.records)
      .filter((record) => isObject(record.value) && record.value.valid === false)
      .map(sourceRecordDiagnostic),
});
