import { join } from "node:path";

import { defineStudioGeneratedTarget } from "../codegen/types";
import type { StudioCodegenTarget, StudioGeneratedTargetDefinition } from "../codegen/types";
import type { ResolvedStudioProjectConfig } from "../config/schema";
import type { StudioHostAppCodegenTargetDefinition } from "../extensions";
import type { loadStudioCatalog } from "../internal/catalog";
import { studioRecordKinds } from "../internal/catalog";
import { displayPath } from "../internal/files";

export type StudioCatalogContent = Awaited<ReturnType<typeof loadStudioCatalog>>;
export type RegisteredGeneratedTarget = StudioGeneratedTargetDefinition<StudioCatalogContent>;

const generatedHeader = (target: StudioCodegenTarget, config: ResolvedStudioProjectConfig) => {
  const template = config.rust?.generatedHeader;
  if (template) {
    return `${template.replaceAll("{target}", target)}\n\n`;
  }

  return `//! Generated by Flexweave Studio for ${target}.\n//! Do not edit manually. Run \`flexweave-studio codegen --target ${target}\` to refresh.\n\n`;
};

const renderRustDefinitions = (
  target: Exclude<StudioCodegenTarget, "reference">,
  records: { id: string; label: string }[],
  config: ResolvedStudioProjectConfig,
) => {
  const entries =
    records.length === 0
      ? "pub const DEFINITIONS: &[(&str, &str)] = &[];\n"
      : [
          "pub const DEFINITIONS: &[(&str, &str)] = &[",
          ...records.map(
            (record) => `    ("${record.id}", "${record.label.replaceAll('"', '\\"')}"),`,
          ),
          "];",
          "",
        ].join("\n");

  return `${generatedHeader(target, config)}${entries}`;
};

const renderReference = (config: ResolvedStudioProjectConfig, catalog: StudioCatalogContent) => {
  const sections = studioRecordKinds.flatMap((kind) => [
    `## ${kind}`,
    "",
    ...(catalog.byKind[kind].length === 0
      ? ["- No records."]
      : catalog.byKind[kind].map((record) => `- ${record.id}: ${record.label}`)),
    "",
  ]);

  return [
    "<!-- Generated by Flexweave Studio. Do not edit manually. -->",
    "",
    "# Studio Catalog Reference",
    "",
    `Config: ${displayPath(config.configDir, config.configPath)}`,
    "",
    ...sections,
  ].join("\n");
};

const generatedTargetLabel = (target: StudioCodegenTarget) =>
  target === "reference" ? "Generated catalog reference" : `Generated ${target} definitions`;

const builtInGeneratedTargets = (
  projectConfig: ResolvedStudioProjectConfig,
): RegisteredGeneratedTarget[] =>
  projectConfig.codegen.builtInTargets.map((target) =>
    defineStudioGeneratedTarget({
      cleanup: "managed-files",
      id: target,
      label: generatedTargetLabel(target),
      plan: ({ config, content, outputDir }) => {
        const resolvedConfig = config as ResolvedStudioProjectConfig;
        const catalog = content as StudioCatalogContent;
        const path =
          target === "reference"
            ? join(outputDir, "studio-reference.md")
            : join(outputDir, "generated.rs");
        const value =
          target === "reference"
            ? renderReference(resolvedConfig, catalog)
            : renderRustDefinitions(target, catalog.byKind[target], resolvedConfig);
        return {
          files: [{ path, value }],
        };
      },
    }),
  );

export const activeGeneratedTargets = (
  config: ResolvedStudioProjectConfig,
): RegisteredGeneratedTarget[] => [
  ...builtInGeneratedTargets(config),
  ...(config.extensions.flatMap(
    (extension) => extension.generatedTargets ?? [],
  ) as RegisteredGeneratedTarget[]),
];

export const activeGeneratedTargetCodegenMetadata = (
  config: ResolvedStudioProjectConfig,
): StudioHostAppCodegenTargetDefinition[] =>
  activeGeneratedTargets(config).map((target) => ({
    label: target.label,
    outputLabel: target.id,
    target: target.id,
  }));
